# Form implementation generated from reading ui file 'C:\Users\phath\PycharmProjects\PhatHuynhProjects\PyQtApplication\1stApplication.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FirstApplication(object):
    def setupUi(self, FirstApplication):
        FirstApplication.setObjectName("FirstApplication")
        FirstApplication.resize(474, 428)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono Light")
        font.setBold(False)
        font.setWeight(50)
        FirstApplication.setFont(font)
        FirstApplication.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=FirstApplication)
        self.buttonBox.setGeometry(QtCore.QRect(150, 390, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=FirstApplication)
        self.label.setGeometry(QtCore.QRect(130, 10, 231, 61))
        font = QtGui.QFont()
        font.setFamily("JetBrainsMonoNL NF Medium")
        self.label.setFont(font)
        self.label.setLineWidth(4)
        self.label.setObjectName("label")

        self.retranslateUi(FirstApplication)
        self.buttonBox.accepted.connect(FirstApplication.accept) # type: ignore
        self.buttonBox.rejected.connect(FirstApplication.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FirstApplication)

    def retranslateUi(self, FirstApplication):
        _translate = QtCore.QCoreApplication.translate
        FirstApplication.setWindowTitle(_translate("FirstApplication", "First Application"))
        self.label.setText(_translate("FirstApplication", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">FIRST APPLICATION</span></p></body></html>"))
